name: m1-a1-streamlit_app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=2.0.0
  - numpy>=1.24.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - streamlit>=1.28.0
  - pyyaml
  - pip
